### ISSUE TITLE
50vs50有大概率会RE

### ISSUE THREAD

**Issue by xiaolan16** [jwcub/fake-generals#11]
50vs50有大概率会RE，导致程序终止。（一周前就有了）
不知道具体问题在哪里
sublime：https://s1.ax1x.com/2020/08/25/dcawsU.png
Dev-C++：https://s1.ax1x.com/2020/08/25/dcd410.png

**Comment by jwcub** [comment]
收到，正在排查

**Comment by xiaolan16** [comment]
我觉得可能是我这的feature

**Comment by jwcub** [comment]
我现在比较忙，预计晚上更新

**Comment by jwcub** [comment]
顺便问一下，其他地图也有这个问题吗？

**Comment by xiaolan16** [comment]
有的，随即和空白都有。迷宫是50VS50根本生成不出来

**Comment by xiaolan16** [comment]
吃鸡好像没有吧，至少目前没遇到过

**Comment by jwcub** [comment]
我这边打了几局，没什么问题

**Comment by jwcub** [comment]
或者您把```Player::botmove()```里面的东西全删掉，再看看会不会出问题

**Comment by xiaolan16** [comment]
我刚试了几局（将botmove里的东西删掉）。
不切屏就好，一切屏就RE。
原本不切屏就可能直接移动不了然后RE

**Comment by jwcub** [comment]
不知道切屏是什么意思。。

**Comment by xiaolan16** [comment]
打开另一个窗口，再回到原来的网页。
看来你对网课的切屏不太熟悉。

**Comment by jwcub** [comment]
那我猜是鼠标选中非法格子的问题

**Comment by jwcub** [comment]
对了，您刚才测试的是什么地图？

**Comment by xiaolan16** [comment]
堑壕

**Comment by jwcub** [comment]
硬盘空间是否不足？

**Comment by xiaolan16** [comment]
应该是够的，每个盘有30多G空的

**Comment by jwcub** [comment]
空白地图有这个问题吗？

**Comment by xiaolan16** [comment]
还没试过，之前有BOT的时候会RE。

**Comment by jwcub** [comment]
那么再试试吧

**Comment by xiaolan16** [comment]
基本每局50vs50都有这样的状况，Dev-C++和sublime都有。我有些无语，但大概是我这的问题吧

**Comment by jwcub** [comment]
我把编译选项的O2关了，也出现了这种问题（Boss模式随机地图）
