### ISSUE TITLE
两个BUG

### ISSUE THREAD

**Issue by xiaolan16** [jwcub/fake-generals#4]
1.在两人占旗模式的总览地图中，被拿了旗的对方基地和队友都是绿色的O
2.占点地图好像不能和大地图搭配

**Comment by xiaolan16** [comment]
第一个说错了，是2v2

**Comment by jwcub** [comment]
1. 总览地图显示的问题，正在修
2. 我这里似乎是可以正常游玩的？请具体描述问题

**Comment by xiaolan16** [comment]
https://cdn.luogu.com.cn/upload/image_hosting/hoy87kkp.png

**Comment by jwcub** [comment]
就是出生后动不了？

**Comment by xiaolan16** [comment]
对，我的config设置如下：
99
99
0.13
0.05
0.05
120
4
2
50
5
20
300

**Comment by jwcub** [comment]
我这边还是可以正常游戏的…您再试几次?

**Comment by xiaolan16** [comment]
啊这，可能是我这C++的feature

**Comment by jwcub** [comment]
修复了总览地图的显示问题
