### ISSUE TITLE
关于wiki

### ISSUE THREAD

**Issue by xiaolan16** [jwcub/fake-generals#5]
wiki当中迷宫的要求是长和宽都为奇数，而不是长宽相等。
我刚才一局100*100发现队友领土一直为2，靠近后发现是不连通（忘记截图了）
所以在wiki当中改一下（我是写checkmate初版迷宫的，所以我知道长宽要都是奇数）

**Comment by xiaolan16** [comment]
顺便建议将总览地图设置放在前面的统一设置，而不是新开一页

**Comment by jwcub** [comment]
感谢反馈，正在修

**Comment by jwcub** [comment]
所有问题都修复了

**Comment by xiaolan16** [comment]
谢谢

**Comment by xiaolan16** [comment]
为了不占用资源，我继续在这个issue提BUG吧：
以下都是对于总览地图：
1.在正常模式且人数较少，标注队友的主基地位置（人数多就不太好）
2.在吃鸡模式，仅标注空投的中心位置，否则可能出现有4个位置是感叹号。
3.确定一个形状的大小顺序，就是说如果一个区域中有两种符号，就要确定哪个在前，哪个在后（就像颜色：当前选中>自己占有的领土其次>队友占领的领土>雾的颜色>空白），形状也要确定这样的顺序
我的建议是：!>+>X>非白色O>F>白色O

**Comment by jwcub** [comment]
好的，正在修复

**Comment by jwcub** [comment]
应该都修好了
